import { Locator, Page } from '@playwright/test';
import { WebPage } from './webPage';
export class NFTgamesPage extends WebPage {
  readonly allFilterButton: Locator;
  readonly avalancheFilterButton: Locator;
  readonly bcsFilterButton: Locator;
  readonly ethFilterButton: Locator;
  readonly hiveFilterButton: Locator;
  readonly polygonFilterButton: Locator;
  readonly roninFilterButton: Locator;
  readonly solanaFilterButton: Locator;
  readonly tezosFilterButton: Locator;
  readonly waxFilterButton: Locator;
  readonly otherFilterButton: Locator;
  readonly expectIfFilterChosen: Locator;
  readonly nameSortButton: Locator;
  readonly expectIfUseSortByName: Locator;
  readonly chainSortButton: Locator;
  readonly expectIfUseSortByChain: Locator;
  readonly categorySortButton: Locator;
  readonly expectIfUseSortByCategory: Locator;
  readonly priceSortButton: Locator;
  readonly expectIfUseSortByPrice: Locator;
  readonly marketCapSortButton: Locator;
  readonly expectIfUseSortByMarketCap: Locator;
  readonly volumeSortButton: Locator;
  readonly expectIfUseSortByVolume: Locator;
  readonly changeSortButton: Locator;
  readonly expectIfUseSortByChange: Locator;
  readonly paginationNextButton: Locator;
  readonly paginationPreviousButton: Locator;
  readonly pagination1button: Locator;
  readonly pagination2button: Locator;
  readonly paginationCurrentbutton: Locator;
  readonly dropdownShowInTheTable: Locator;
  readonly expectedIfChosen25InDopdownShow: Locator;
  readonly expectedIfChosen50InDopdownShow: Locator;
  readonly expectedIfChosen100InDopdownShow: Locator;
  readonly expectedIfChosen10InDopdownShow: Locator;
  readonly leftButtonInTheCarousel: Locator;
  readonly rightButtonInTheCarousel: Locator;
  readonly expectedIfUseLeftButtonInTheCarusel: Locator;
  readonly expectedIfUseRightButtonInTheCarusel: Locator;
  readonly readMoreButton: Locator;
  readonly readLessButton: Locator;
  readonly readMoreOrLessWhatIsNFTgamingButton: Locator;
  readonly expectReadMoreOrLessWhatIsNFTgamingText: Locator;
  readonly readMoreOrLessHowDoIEarnMoneyThroughNFTgamingButton: Locator;
  readonly expectReadMoreHowDoIEarnMoneyThroughNFTgamingText: Locator;
  readonly readMoreOrLessHowManyNFTgamesAreThereButton: Locator;
  readonly expectReadMoreOrLessHowManyNFTgamesAreThereText: Locator;
  readonly readMoreOrLessCanIearnMoneyThroughNFTgamingButton: Locator;
  readonly expectReadMoreOrLessCanIearnMoneyThroughNFTgamingText: Locator;

  constructor(page: Page) {
    super(page);
    this.allFilterButton = page.locator('[data-cat="all"]');
    this.avalancheFilterButton = page.locator('[data-cat="avalanche"]');
    this.bcsFilterButton = page.locator('[data-cat="bsc"]');
    this.ethFilterButton = page.locator('[data-cat="eth"]');
    this.hiveFilterButton = page.locator('[data-cat="hive"]');
    this.polygonFilterButton = page.locator('[data-cat="polygon"]');
    this.roninFilterButton = page.locator('[data-cat="ronin"]');
    this.solanaFilterButton = page.locator('[data-cat="solana"]');
    this.tezosFilterButton = page.locator('[data-cat="tezos"]');
    this.waxFilterButton = page.locator('[data-cat="wax"]');
    this.otherFilterButton = page.locator('[data-cat="other"]');
    this.expectIfFilterChosen = page.locator('(//td[@data-label="Chain"])[1]');
    this.nameSortButton = page.locator('(//th[@aria-controls="DataTables_Table_0"])[1]');
    this.expectIfUseSortByName = page.locator('//h3[contains(text(),"A")]');
    this.chainSortButton = page.locator('(//th[@aria-controls="DataTables_Table_0"])[2]');
    this.expectIfUseSortByChain = page.locator('//td[contains(text(),"A")]');
    this.categorySortButton = page.locator('(//th[@aria-controls="DataTables_Table_0"])[3]');
    this.expectIfUseSortByCategory = page.locator('//td[contains(text(),"C")]');
    this.priceSortButton = page.locator('(//th[@aria-controls="DataTables_Table_0"])[4]');
    this.expectIfUseSortByPrice = page.locator('//td[contains(text()," ")]');
    this.marketCapSortButton = page.locator('(//th[@aria-controls="DataTables_Table_0"])[5]');
    this.expectIfUseSortByMarketCap = page.locator('//td[contains(text()," ")]');
    this.volumeSortButton = page.locator('(//th[@aria-controls="DataTables_Table_0"])[6]');
    this.expectIfUseSortByVolume = page.locator('//td[contains(text()," ")]');
    this.changeSortButton = page.locator('(//th[@aria-controls="DataTables_Table_0"])[7]');
    this.expectIfUseSortByChange = page.locator('//td[contains(text()," ")]');
    this.paginationNextButton = page.locator('[class="paginate_button next"]');
    this.paginationPreviousButton = page.locator('[class="paginate_button previous"]');
    this.pagination1button = page.locator('[data-dt-idx="1"]');
    this.pagination2button = page.locator('[data-dt-idx="2"]');
    this.paginationCurrentbutton = page.locator('[class="paginate_button current"]');
    this.dropdownShowInTheTable = page.locator('select[name="DataTables_Table_0_length"]');
    this.expectedIfChosen25InDopdownShow = page.locator('(//div[@class="filter-name__detail"])[25]');
    this.expectedIfChosen50InDopdownShow = page.locator('(//div[@class="filter-name__detail"])[50]');
    this.expectedIfChosen100InDopdownShow = page.locator('(//div[@class="filter-name__detail"])[100]');;
    this.expectedIfChosen10InDopdownShow = page.locator('(//div[@class="filter-name__detail"])[10]');
    this.leftButtonInTheCarousel = page.locator('[class="icon icon-arrow-left"]');
    this.rightButtonInTheCarousel = page.locator('[class="slick-next slick-arrow"]');
    this.expectedIfUseLeftButtonInTheCarusel = page.locator('(//h3[contains(text(),"Thetan Arena")])[1]');
    this.expectedIfUseRightButtonInTheCarusel = page.locator('(//h3[contains(text(),"Splinterlands")])[1]');
    this.readMoreButton = page.locator('[class="icon icon-angle-down"]');
    this.readLessButton = page.locator('[class="icon icon-angle-down"]');
    this.readMoreOrLessWhatIsNFTgamingButton = page.locator('(//span[@class="faq-item__toggle-icon"])[1]');
    this.expectReadMoreOrLessWhatIsNFTgamingText = page.locator('text=NFT gaming is playing NFT games');
    this.readMoreOrLessHowDoIEarnMoneyThroughNFTgamingButton = page.locator('(//span[@class="faq-item__toggle-icon"])[2]');
    this.expectReadMoreHowDoIEarnMoneyThroughNFTgamingText = page.locator('text=For most NFT games out there');
    this.readMoreOrLessHowManyNFTgamesAreThereButton = page.locator('(//span[@class="faq-item__toggle-icon"])[3]');
    this.expectReadMoreOrLessHowManyNFTgamesAreThereText = page.locator('text=There are tons of different NFT games');
    this.readMoreOrLessCanIearnMoneyThroughNFTgamingButton = page.locator('(//span[@class="faq-item__toggle-icon"])[4]');
    this.expectReadMoreOrLessCanIearnMoneyThroughNFTgamingText = page.locator('text=Yes, you can earn money through NFT gaming');
  }

}
